indexcheck/urls.py
from django.urls import path
from . import views


app_name = 'indexcheck'

urlpatterns = [
    path('', views.index_list, name='index_list'),
    path('detail/<int:pk>/', views.index_detail, name='index_detail'),
    path('create/', views.index_create, name='index_create'),
    path('update/<int:pk>/', views.index_update, name='index_update'),
    path('delete/<int:pk>/', views.index_delete, name='index_delete'),
    path('plot/<int:pk>/', views.get_svg, name='index_plot'),
    path('signup/', views.signup, name='signup'),
    path('hello/', views.hello, name='hello'),
    ]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('indexcheck.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

indexcheck/models.py
from django.db import models
from django.utils import timezone
from django_mysql.models import ListCharField

class Indexcheck(models.Model):
    theme_name = models.CharField('テーマ名', max_length=255)
    code = ListCharField(
        models.CharField('コード', max_length=255,), max_length=(1 * 15))
    created_at = models.DateTimeField('作成日', default=timezone.now)
    #comment = models.TextField('コメント', blank=True)

    def __str__(self):
        return self.theme_name

indexcheck/forms.py
from django import forms
from .models import Indexcheck

class IndexCreateForm(forms.ModelForm):

    class Meta:
        model = Indexcheck
        exclude = ('created_at',)
        fields = ('theme_name', 'code')

from django.contrib.auth.forms import UserCreationForm

# ユーザ作成フォームを継承
class SignUpForm(UserCreationForm):
    username = forms.CharField()
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

indexcheck/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Indexcheck
from .forms import IndexCreateForm

import pandas as pd
import pandas_datareader.data as web
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime
from datetime import date
from datetime import timedelta
from urllib.request import urlopen
from bs4 import BeautifulSoup
from pandas.plotting import register_matplotlib_converters
register_matplotlib_converters()

import requests
import json
import matplotlib
matplotlib.use('Agg')

import io
from django.http import HttpResponse

from .forms import SignUpForm



def index_list(request):
    context = {
        'index_list':Indexcheck.objects.all().order_by('created_at'),
    }
    return render(request, 'indexcheck/index_list.html', context)

def index_detail(request, pk):
    context = {
        'index': get_object_or_404(Indexcheck, pk=pk)
    }
    return render(request, 'indexcheck/index_detail.html', context)

def index_create(request):
    form = IndexCreateForm(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('indexcheck:index_list')

    context = {
        'form': form
    }
    return render(request, 'indexcheck/index_form.html', context)

def index_update(request, pk):
    index = get_object_or_404(Indexcheck, pk=pk)
    form = IndexCreateForm(request.POST or None, instance=index)
    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('indexcheck:index_list')

    context = {
        'form':form
    }
    return render(request, 'indexcheck/index_form.html', context)

def index_delete(request, pk):
    index = get_object_or_404(Indexcheck, pk=pk)
    if request.method =='POST':
        index.delete()
        return redirect('indexcheck:index_list')

    context = {
        'index': index
    }
    return render(request, 'indexcheck/index_confirm_delete.html', context)

def setPlt(request, pk):
    #theme = Indexcheck.objects.values_list('theme_name').get(pk=pk)
    l = Indexcheck.objects.values_list('code', flat=True).get(pk=pk)
    l = list(l)

    td = date.today()
    md = timedelta(weeks=18)
    st_dt = td - md #@param {type:'date'}
        

    data = web.DataReader([str(c) + '.JP' for c in l], 'stooq')

    dt0 = pd.DataFrame(data.index)

    def cook(code):
        try:
            tgt = 'https://kabutan.jp/stock/kabuka?code=' + str(code)
            html = urlopen(tgt)
            bsObj = BeautifulSoup(html, 'html.parser')
            table = bsObj.findAll('table', {'class':'stock_kabuka0'})[0]
            rows = table.findAll('tr')
            for row in rows:
                rec = []
                for cell in row.findAll(['td', 'th']):
                    rec.append(cell.get_text())
                del rec[5:7]
                rec.insert(0, str(code) + '.JP')
            dish.append(rec)
            return 'Success'
        except Exception as e:
            return str(code) + ': ' + str(e)
        
    dish = []
    [cook(i) for i in l]

    df10 = pd.DataFrame(dish).rename(columns={0: 'code', 1: 'Date', 2:'Open', 3: 'High', 4: 'Low', 5:'Close', 6: 'Volume'})
        
    dt_fmt = lambda dt_str: datetime.strptime(dt_str, '%y/%m/%d')

    df10['Date'] = df10['Date'].map(dt_fmt)

    def conv(dfn, col, typ):
        try:
            dfn[col] = dfn[col].astype(typ)
        except:
            dfn[col] = dfn[col].str.replace(',', '').astype(typ)
        finally:
            return 'Success'
        
    cols = ['code', 'Date', 'Open', 'High', 'Low', 'Close', 'Volume'] 

    [conv(df10, j, float) for j in cols[2:]]

    output = pd.DataFrame(index=[], columns=cols)

    for c in l:
        try:
            vec = []
            ex_values = lambda x: vec.append(data[x, str(c) + '.JP'].values.tolist())
            [ex_values(x) for x in cols[2:]] 

            df0 = pd.DataFrame(vec).T.rename(columns={0:'Open', 1:'High', 2:'Low', 3:'Close', 4:'Volume'})
            df1 = pd.merge(dt0, df0, left_index=True, right_index=True).query('Date >= @st_dt').dropna().reset_index().drop(columns='index')

            df11 = df10[df10['code'] == str(c) + '.JP'].drop(columns='code')

            df = df1.append(df11, ignore_index=True, sort=False)
            df['code'] = c

            output = output.append(df[cols])
        except Exception as e:
            print(str(c) + ': ' + e)
            
    output2 = output.drop(['Open','High','Low','Volume'], axis = 1)

    cols = []
    for i in range(0,len(l)):
        qs = 'code == @l[{0}]'.format(i)
        col = output2.query(qs).drop(columns='code').rename(columns={'Close':l[i]})
        col.set_index('Date', inplace=True)
        cols.append(col)

    output = pd.concat(cols, axis=1)  
    output = output.sort_index()
    
    output3 = np.log(output)
    output4 = output3.diff().fillna(0) + 1
    output5 = output4.cumprod()
    output6 = output5.drop(columns = l[0])
    topix = pd.DataFrame(output5[l[0]])
    output6["theme_avg"] = output6.mean(axis=1)
    theme_avg = pd.DataFrame(output6["theme_avg"])
    output7 = pd.concat([topix, theme_avg], axis=1)
    output7['Index'] = output7['theme_avg']/output7[l[0]]
    output8 = output7.drop(columns = ['theme_avg', l[0]])

    fig,ax = plt.subplots()
    ax.plot(output8.index, output8)
    ax.grid(True)
    #ax.set_title(theme, fontname="MS Gothic")
    plt.setp(ax.get_xticklabels(), rotation=60, ha="right")

def plt_svg():
    buf = io.BytesIO()
    plt.savefig(buf, format='svg', bbox_inches='tight')
    s = buf.getvalue()
    buf.close()
    return s

def get_svg(request, pk):
    setPlt(request, pk)  
    svg = plt_svg()  #SVG化
    plt.cla()  # グラフをリセット
    response = HttpResponse(svg, content_type='image/svg+xml')
    return response

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect(to='indexcheck/index_list.html')
    else:
        form = SignUpForm()
    return render(request, 'indexcheck/signup.html', {'form': form})

def hello(request):
    name = request.user
    print(name)
    return render(request, 'indexcheck/hello.html', {'name': name})

indexcheck/templates/indexcheck/base.html
{% load static %}

{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Indexcheck</title>
  <link rel="stylesheet" href="{% static 'indexcheck/css/bootstrap.min.css' %}">
  <!-- plugins:css -->
  <link rel="stylesheet" href="{% static 'indexcheck/vendors/mdi/css/materialdesignicons.min.css' %}">
  <link rel="stylesheet" href="{% static 'indexcheck/vendors/css/vendor.bundle.base.css' %}">
  <!-- endinject -->
  <!-- Plugin css for this page -->
  <link rel="stylesheet" href="{% static 'indexcheck/vendors/flag-icon-css/css/flag-icon.min.css' %}">
  <link rel="stylesheet" href="{% static 'indexcheck/vendors/jvectormap/jquery-jvectormap.css' %}">
  <!-- End plugin css for this page -->
  <!-- Layout styles -->
  <link rel="stylesheet" href="{% static 'indexcheck/css/demo/style.css' %}">
  <!-- End layout styles -->
  <link rel="shortcut icon" href="{% static 'indexcheck/images/favicon.png' %}" />
</head>
<body>
<script src="{% static 'indexcheck/js/preloader.js'%}"></script>
{% if user.is_authenticated %}
  <div class="body-wrapper">
    <aside class="mdc-drawer mdc-drawer--dismissible mdc-drawer--open">
      <div class="mdc-drawer__header">
        <a class="mdc-drawer__header-name" href="{% url 'indexcheck:index_list' %}">Indexcheck</a>
      </div>
      <div class="mdc-drawer__content ps">
        <div class="user-info">
          <p class="name">{{ user.username }}</p>
          <p class="email">xxxxx@example</p>
        </div>
        <div class="mdc-list-group">
          <nav class="mdc-list mdc-drawer-menu">
            <div class="mdc-list-item mdc-drawer-item" tabindex="-1">
              <a class="mdc-drawer-link active" href="{% url 'indexcheck:index_list' %}" tabindex="-1">
                <i class="material-icons mdc-list-item__start-detail mdc-drawer-item-icon" aria-hidden="true">home</i>
                  List
              </a>
            </div>
            <div class="mdc-list-item mdc-drawer-item" tabindex="-1">
              <a class="mdc-drawer-link active" href="{% url 'indexcheck:index_create' %}" tabindex="-1">
                <i class="material-icons mdc-list-item__start-detail mdc-drawer-item-icon" aria-hidden="true">track_changes</i>
                  Create
              </a>
            </div>
          </nav> 
        </div>
        <div class="ps__rail-x" style="left: 0px; bottom: 0px;">
          <div class="ps__thumb-x" tabindex="0" style="left: 0px; width: 0px;"></div>
        </div>
        <div class="ps__rail-y" style="top: 0px; right: 0px;">
          <div class="ps__thumb-y" tabindex="0" style="top: 0px; height: 0px;"></div>
        </div>
      </div>
    </aside>
    <div class="main-wrapper mdc-drawer-app-content">
      <header class="mdc-top-app-bar">
        <div class="mdc-top-app-bar__row">
          <div class="mdc-top-app-bar__section mdc-top-app-bar__section--align-start">
            <button class="material-icons mdc-top-app-bar__navigation-icon mdc-icon-button sidebar-toggler">menu</button>
            <span class="mdc-top-app-bar__title">Indexcheck</span>
          </div>
          <div class="mdc-top-app-bar__section mdc-top-app-bar__section--align-end mdc-top-app-bar__section-right">
            <div class="menu-button-container menu-profile d-none d-md-block">
              <button class="mdc-button mdc-menu-button">
                <span class="d-flex align-items-center">
                  <span class="user-name">{{ user.username }}</span>
                </span>
              </button>
              <div class="mdc-menu mdc-menu-surface" tabindex="-1">
                <ul class="mdc-list" role="menu" aria-hidden="true" aria-orientation="vertical">
                  <li class="mdc-list-item" role="menuitem">
                    <div class="item-thumbnail item-thumbnail-icon-only">
                      <i class="mdi mdi-account-edit-outline text-primary"></i>
                    </div>
                    <div class="item-content d-flex align-items-start flex-column justify-content-center">
                      <h6 class="item-subject font-weight-normal">Edit profile</h6>
                    </div>
                  </li>
                  <li class="mdc-list-item" role="menuitem">
                    <div class="item-thumbnail item-thumbnail-icon-only">
                      <i class="mdi mdi-settings-outline text-primary"></i>                      
                    </div>
                    <!--<div class="item-content d-flex align-items-start flex-column justify-content-center">
                      <h6 class="item-subject font-weight-normal"> Log out</h6>
                    </div>-->
                    <a class="item-subject font-weight-normal" href="{% url 'logout' %}"> Log out</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </header>
      <div class="page-wrapper mdc-toolbar-fixed-adjust">
        <main class="content-wrapper">
          <div class="mdc-layout-grid">
            <div class="mdc-layout-grid__inner">
              {% block content %}{% endblock %}
            </div>
          </div>
        </main>
      </div>
    </div>
  </div>
  {% else %}
  <p>ログインしていません</p>
  <p><a href="{% url 'login' %}">ログインする</a></p>
  {% endif %}
  <!--<script src="{% static 'indexcheck/js/jquery-3.5.0.min.js' %}"></script>-->
  <script src="{% static 'indexcheck/js/bootstrap.bundle.min.js' %}"></script>
  <!-- plugins:js -->
  <script src="{% static 'indexcheck/vendors/js/vendor.bundle.base.js' %}"></script>
  <!-- endinject -->
  <!-- Plugin js for this page-->
  <script src="{% static 'indexcheck/vendors/chartjs/Chart.min.js' %}"></script>
  <script src="{% static 'indexcheck/vendors/jvectormap/jquery-jvectormap.min.js' %}"></script>
  <script src="{% static 'indexcheck/vendors/jvectormap/jquery-jvectormap-world-mill-en.js' %}"></script>
  <!-- End plugin js for this page-->
  <!-- inject:js -->
  <script src="{% static 'indexcheck/js/material.js' %}"></script>
  <script src="{% static 'indexcheck/js/misc.js' %}"></script>
  <!-- endinject -->
  <!-- Custom js for this page-->
  <script src="{% static 'indexcheck/js/dashboard.js' %}"></script>
  <!-- End custom js for this page-->
</body>
</html>



indexcheck/templates/indexcheck/hello.html
{% extends 'indexcheck/base.html' %}

{% block content %}
<div class="mdc-layout-grid__cell--span-12">
  <div class="mdc-card p-0">
    <section class="error-header">
      <h6 class="card-title">Welcome!</h6>
    </section>
    <section class="error-info">
      <p>Hello! {{ name }}</p>
    </section>
  </div>
</div>
{% endblock %}

indexcheck/templates/indexcheck/index_confirm_delete.html
{% extends 'indexcheck/base.html' %}

{% block content %}
  <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
    <div class="mdc-card">
      <p>{{ index.theme_name }}を削除します。よろしいですか。</p>
      <form action="" method="POST">
          {% csrf_token %}
          <button class="mdc-button mdc-button--unelevated filled-button--secondary" type="submit">削除</button>
      </form>
    </div>
  </div>
{% endblock %}

indexcheck/templates/indexcheck/index_detail.html
{% extends 'indexcheck/base.html' %}

{% block content %}
  <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
    <div class="mdc-card">
      <div class="d-flex justify-content-between">
        <h4 class="card-title mb-0">{{ index.theme_name }}</h4>
      </div>
      <div class="d-block d-sm-flex justify-content-between align-items-center">
        <h5 class="card-sub-title mb-2 mb-sm-0">{{ index.code }}</h5>
      </div>
      <div class="mdc-layout-grid__inner mt-2">
        <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-6 mdc-layout-grid__cell--span-8-tablet">
          <img src="{% url 'indexcheck:index_plot' index.pk %}" width=600 height=600>
        </div>
      </div>
      <div class="d-block d-sm-flex">
        <a class="mdc-button mdc-button--unelevated filled-button--info" href="{% url 'indexcheck:index_update' index.pk %}">
          編集
        </a>
        <a class="mdc-button mdc-button--unelevated filled-button--secondary" href="{% url 'indexcheck:index_delete' index.pk %}">
          削除
        </a>
      </div>
    </div>
   </div>
{% endblock %}

indexcheck/templates/indexcheck/index_form.html
{% extends 'indexcheck/base.html' %}
{% load widget_tweaks %}

{% block content %}
  <div class="mdc-layout-grid__cell--span-12">
    <div class="mdc-card">
      <h6 class="card-title">Information</h6>
      <div class="template-demo">
        <div class="mdc-layout-grid__inner">
          <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6-desktop">
          <form action="" method="POST">  
            {% csrf_token %}
            <div class="mdc-text-field mdc-text-field--outlined">
              {{ form.theme_name|add_class:'mdc-text-field__input' }}
                <div class="mdc-notched-outline">
                  <div class="mdc-notched-outline__leading"></div>
                  <div class="mdc-notched-outline__notch">
                    <label for="text-field-hero-input" class="mdc-floating-label">テーマ名</label>
                  </div>
                  <div class="mdc-notched-outline__trailing"></div>
                </div>    
            </div>
            <div class="mdc-text-field mdc-text-field--outlined">
              {{ form.code|add_class:'mdc-text-field__input' }}
                <div class="mdc-notched-outline">
                  <div class="mdc-notched-outline__leading"></div>
                  <div class="mdc-notched-outline__notch">
                    <label for="text-field-hero-input" class="mdc-floating-label">コード</label>
                  </div>
                  <div class="mdc-notched-outline__trailing"></div>
                </div>    
            </div>
            <!--<div class="mdc-text-field2 mdc-text-field2--outlined">
              {{ form.comment|add_class:'mdc-text-field2__input' }}
                <div class="mdc-notched-outline">
                  <div class="mdc-notched-outline__leading"></div>
                  <div class="mdc-notched-outline__notch">
                    <label for="text-field-hero-input" class="mdc-floating-label">コメント</label>
                  </div>
                  <div class="mdc-notched-outline__trailing"></div>
                </div>   
            </div>-->
            <p>{{ form.instance.created_at }}</p>
            <button class="mdc-button mdc-button--unelevated filled-button--dark mdc-ripple-upgraded" type="submit">リストに追加</button>
          </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

indexcheck/templates/indexcheck/index_list.html
{% extends 'indexcheck/base.html' %}

{% block content %}
  <h2>Index List</h2>
  {% for index in index_list %}
    <div class="card-inner">
      <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-3-desktop mdc-layout-grid__cell--span-4-tablet">
        <div class="mdc-card info-card info-card--success">
          <div class="card-inner">
            <h3 class="card-title">{{ index.theme_name }}</h3>
            <h5 class="font-weight-light pb-2 mb-1 border-bottom">{{ index.code }}</h5>
            <a class="mdc-button mdc-button--unelevated" href="{% url 'indexcheck:index_detail' index.pk %}">
              グラフ
            </a>
            <a class="mdc-button mdc-button--unelevated filled-button--info" href="{% url 'indexcheck:index_update' index.pk %}">
              編集
            </a>
            <a class="mdc-button mdc-button--unelevated filled-button--secondary" href="{% url 'indexcheck:index_delete' index.pk %}">
              削除
            </a>
          </div>
        </div>
      </div>
    </div>
  {% endfor %}
{% endblock %}

indexcheck/templates/indexcheck/signup.html
{% extends 'indexcheck/base.html' %}
{% load widget_tweaks %}

{% block content %}
{{ form.as_p }}
{% endblock %}